version: "3.9"

services:
  front-next:
    container_name: front-next
    image: front-next
    restart: unless-stopped
    build:
      context: ./
      dockerfile: next.dockerfile
    env_file:
      - .env
    expose:
      - ${NEXT_PORT}
    environment:
      PORT: ${NEXT_PORT}

  front-nginx:
    container_name: front-nginx
    image: nginx:stable-alpine3.17
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/next-server.conf:/etc/nginx/conf.d/next-server.conf
      - ./nginx/next-upstream.conf.template:/etc/nginx/templates/next-upstream.conf.template
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
      - ./.logs:/etc/nginx/logs
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
      NEXT_PORT: ${NEXT_PORT}
